apiVersion: batch/v1
kind: Job
metadata:
  name: grafana
  namespace: {{ .Values.namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      name: grafana
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      serviceAccount: {{ .Values.serviceAccount.name }}
      containers:
      - name: grafana-sa-job
        image: alpine:latest
        command: ["/grafana-sa/create_service_account.sh"]
        volumeMounts:
        - name: grafana-sa-script
          mountPath: /grafana-sa
      volumes:
        - name: grafana-sa-script
          configMap:
             name: grafana-sa-script
             defaultMode: 0755
      restartPolicy: OnFailure