apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.cert_issuer_name }}
  labels:
    system.api: "true"
spec:
  acme:
    email: {{ .Values.domain_admin_email }}
    server: {{.Values.letsencrypt_server_url }}
    privateKeySecretRef:
      name: {{ .Values.cert_issuer_name }}
    solvers:
    - http01:
        ingress:
          ingressClassName: {{ .Values.ingress_class_name }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.cert_name }}
  namespace: {{ $.Values.default_namespace }}
  labels:
    system.api: "true"
spec:
  secretName: {{ $.Values.cert_name }}
  commonName: {{ $.Values.domain }}
  dnsNames:
    - {{ $.Values.domain }}
  issuerRef:
    name: {{ $.Values.cert_issuer_name }}
    kind: {{ $.Values.cert_issuer_type }}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ join "," $.Values.cert_namespaces }}
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

{{- if .Values.keycloak.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.cert_name }}
  namespace: {{ $.Values.keycloak.namespace }}
  labels:
    system.api: "true"
spec:
  secretName: {{ $.Values.cert_name }}
  commonName: "auth.{{ $.Values.domain }}"
  dnsNames:
    - "auth.{{ $.Values.domain }}"
  issuerRef:
    name: {{ $.Values.cert_issuer_name }}
    kind: {{ $.Values.cert_issuer_type }}
{{- end }}