apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.namespace }}
  labels:
    app: flink
    system.processing: "true"
data:
  log4j_console_properties: |+
{{ .Values.log4j_console_properties | indent 4 }}