namespace: "web-console"
replicaCount: 1
image: 
  repository: sunbird
  image_name: sb-obsrv-web-console
  tag: "1.0.0"
  pullPolicy: "IfNotPresent"
ENV: development
PORT: 3000
APP_NAME: obsrv-web-console
PROMETHEUS_URL: http://localhost
HTTPS: false
REACT_APP_VERSION: v1.2.0
GENERATE_SOURCEMAP: false
REACT_APP_GRAFANA_URL: http://localhost
REACT_APP_SUPERSET_URL: http://localhost