{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flink-sa.serviceAccountName" . }}
  labels:
    {{- include "flink-sa.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
    system.processing: "true"
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}