{{- range $jobName, $jobData := .Values.flink_jobs }}
{{- if $jobData.enabled }}
{{- $components := list "jobmanager" "taskmanager" }}
{{- range $component := $components }}
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "base.namespace" $}}
  name: {{ $jobName }}-{{ $component }}
  labels:
    {{- include "common.labels.standard" (dict "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
    component: {{ printf "%s-%s" $jobName $component }}

  {{- if $.Values.commonAnnotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    {{- if eq $component "jobmanager" }}
    - name: rpc
      port: {{ $.Values.jobmanager.rpc_port }}
    - name: blob
      port: {{ $.Values.jobmanager.blob_port }}
    - name: query
      port: {{ $.Values.jobmanager.query_port }}
    - name: ui
      port: {{ $.Values.jobmanager.ui_port }}
    - name: prom
      port: {{ $.Values.jobmanager.prom_port }}
    {{- else if eq $component "taskmanager" }}
    - name: prom
      port: {{ $.Values.taskmanager.prom_port }}
    {{- end }}
  selector:
    app.kubernetes.io/component: {{ $jobName }}-{{ $component }}
{{- end }}
{{- end }}
{{- end }}