apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
kind: Secret
metadata:
  name: {{ .Values.docker_registry_secret_name }}
  namespace: {{ .Release.namespace }}
type: kubernetes.io/dockerconfigjson