# Default values for kafka-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: kafka
image:
  repository: danielqsj/kafka-exporter
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9308

kafkaExporter:
  kafka:
    servers: ["kafka-headless:9093"]
  zookeeper:
    servers: ["kafka-zookeeper-headless.svc.cluster.local:2181"]
  additionalFlags: []
    # - --use.consumelag.zookeeper

  sasl:
    enabled: false
    handshake: true
    username: ""
    password: ""

  tls:
    enabled: false
    insecure-skip-tls-verify: false
    caFile: ""
    certFile: ""
    keyFile: ""

  log:
    level: info
    enableSarama: false

prometheus:
  serviceMonitor:
    enabled: true
    namespace: kafka
    interval: "30s"
    additionalLabels:
      app: kafka-exporter
      system.monitoring: "true"
      release: monitoring

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
