# Default values for kafka-message-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: "sanketikahub/kafka-message-exporter"
  pullPolicy: IfNotPresent
  imagePullSecrets: ""
  tag: "1.0.0-GA"

nameOverride: ""
fullnameOverride: "kafka-message-exporter"
replicaCount: 1

service:
  type: ClusterIP
  port: 8000

podAnnotations: {}


config:
  kafka:
    spark:
      host: "kafka-headless.kafka.svc.cluster.local:9092"
      topic: "spark.stats"
      schema: "telemetry"
    obsrv:
      host: "kafka-headless.kafka.svc.cluster.local:9092"
      topic: "sb-dev.stats"
      schema: "obsrv_meta"

serviceMonitorLabels: {}
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
