{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "base.namespace" . }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    "helm.sh/hook-weight": "-5"
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
{{- $currentScope := .}}
{{- range $path, $_ := .Files.Glob "configs/*" }}
  {{- if ne $path "configs/env.yaml" }}
    {{ base $path | nindent 2 }}: |-
      {{- with $currentScope }}
      {{- $var := .Files.Get $path }}
      {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 6 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-env
  namespace: {{ include "base.namespace" . }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    "helm.sh/hook-weight": "-5"
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  {{- $var := .Files.Get "configs/env.yaml" }}
  {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 2 }}
---
{{- $currentScope := .}}
{{- range $folder := .Values.migration_folder_list }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" $ }}-{{ $folder }}
  namespace: {{ include "base.namespace" $ }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" $.Values.commonLabels "context" $) | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations:
    "helm.sh/hook-weight": "-5"
{{ include "common.tplvalues.render" (dict "value" $.Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
{{- $globPath := printf "configs/migrations/%s/*" $folder }}
{{- range $path, $_ := $.Files.Glob $globPath }}
  {{ base $path | nindent 2 }}: |-
    {{- with $currentScope }}
    {{- $var := .Files.Get $path }}
    {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 6 }}
    {{- end }}
{{- end }}
---
{{- end }}
