{{- if not (or .Values.config.datasource.passwordSecret .Values.config.datasourceSecret .Values.config.datasource.passwordFile ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  namespace: {{ include "base.namespace" . }}
  labels:
    app: {{ template "prometheus-postgres-exporter.name" . }}
    chart: {{ template "prometheus-postgres-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  data_source_password: {{ (.Values.config.datasource.password | default .Values.global.postgresql.password ) | b64enc }}
{{- end -}}
