apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
kind: Secret
metadata:
  name: {{ .Values.docker_registry_secret_name }}
  namespace: {{ .Values.namespace }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "{{ .Values.allowed_namespaces }}"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "{{ .Values.allowed_namespaces }}"
type: kubernetes.io/dockerconfigjson