kind: ConfigMap
apiVersion: v1
metadata:
  name: flyway-postgresql-cm
  namespace: {{ .Values.namespace }}
  labels:
    name: flyway-postgresql-cm
    app: flyway-postgresql
data:
  FLYWAY_URL: {{ .Values.config.db.url }}
  FLYWAY_USER: {{ .Values.config.db.username }}
  FLYWAY_PASSWORD: {{ .Values.config.db.password }}
  driver-class-name: {{ .Values.config.db.driver_class_name }}
  PGPASSWORD: {{ .Values.config.db.password }}