kind: ConfigMap
apiVersion: v1
metadata:
  name: superset-sql-files
  namespace: {{ .Values.namespace }}
  labels:
    name: superset-sql-files
    app: flyway-postgresql
data:
  {{- (tpl (.Files.Glob "migration/01_superset/*.sql").AsConfig .) | nindent 2 }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: druid-raw-sql-files
  namespace: {{ .Values.namespace }}
  labels:
    name: druid-raw-sql-files
    app: flyway-postgresql
data:
  {{- (tpl (.Files.Glob "migration/02_druid_raw/*.sql").AsConfig .) | nindent 2 }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: obsrv-sql-files
  namespace: {{ .Values.namespace }}
  labels:
    name: obsrv-sql-files
    app: flyway-postgresql
data:
  {{- (tpl (.Files.Glob "migration/03_obsrv/*.sql").AsConfig .) | nindent 2 }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: keycloak-sql-files
  namespace: {{ .Values.namespace }}
  labels:
    name: keycloak-sql-files
    app: flyway-postgresql
data:
  {{- (tpl (.Files.Glob "migration/04_keycloak/*.sql").AsConfig .) | nindent 2 }}


---
{{- if .Values.enable_lakehouse }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: hms-sql-files
  namespace: {{ .Values.namespace }}
  labels:
    name: hms-sql-files
    app: flyway-postgresql
data:
  {{- (tpl (.Files.Glob "migration/05_hms/*.sql").AsConfig .) | nindent 2 }}
{{- end }}