{{- if .Values.service_account_annotations -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
  namespace: {{ .Values.namespace }}
  annotations:
    {{ toYaml .Values.service_account_annotations }}
{{- end -}}