{{- $currentScope := .}}
{{- range $jobName, $jobData := .Values.secor_jobs }}
{{- if $jobData.enabled }}
{{- with $currentScope }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: {{ $jobName }}-config
  name: {{ $jobName }}
  namespace: {{ include "base.namespace" . }}
  labels:
    app: secor
    system.storage: "true"
spec:
  serviceName: secor
  updateStrategy:
    type: RollingUpdate
  replicas: {{ $jobData.replicas }}
  selector:
    matchLabels:
      app: secor
      release: {{ $jobName }}
  template:
    metadata:
      labels:
        app: secor
        release: {{ $jobName }}
    spec:
      {{- if .Values.serviceAccount.create}}
      serviceAccountName: {{ include "base.serviceaccountname" . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: change-pv-dir-ownership
        image: alpine:3
        command: ["/bin/sh", "-c"]
        args: ["chown -R 9999:9999 /mnt/data"]
        volumeMounts:
        - name: data-path
          mountPath: /mnt/data
      containers:
        - name: {{ $jobName }}-secor
          image: "{{ include "base.image" . }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: "CONFIG_FILE"
              value: "/opt/secor/config/secor.partition.properties"
            - name: "LOG4J_CONFIGURATION"
              value: "/opt/secor/config/log4j.docker.properties"
            - name: "JVM_MEMORY"
              value: "{{ .Values.jvm_memory }}"
            - name: "TIMEZONE"
              value: "{{ .Values.timezone }}"  
          volumeMounts:
           - mountPath: /opt/secor/config
             name: secor-config
           - name: "data-path"
             mountPath: /mnt/data
          resources:
            limits:
              cpu: {{ get (get (get $.Values.secor_jobs $jobName) "limits") "cpu" }}
              memory: {{ get (get (get $.Values.secor_jobs $jobName) "limits") "memory"}}
            requests:
              cpu: {{ get (get (get $.Values.secor_jobs $jobName) "requests") "cpu" }}
              memory: {{ get (get (get $.Values.secor_jobs $jobName) "requests") "memory"}}
          securityContext:
            runAsUser: 9999

      volumes:
        - configMap:
            name: {{ $jobName }}-config
          name: secor-config

  volumeClaimTemplates:
    - metadata:
        name: data-path
        labels:
          app: secor
          system.storage: "true"
      spec:
        {{- if .Values.storageClass }}
        storageClassName: "{{- .Values.storageClass }}"
        {{- end }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ $jobData.storage.size }}
{{- end }}
{{- end }}
{{- end }}
