namespace: "web-console"
replicaCount: 1
cpu_requests: 0.25
cpu_limits: 0.5
memory_requests: 256Mi
memory_limits: 512Mi
image:
  repository: sunbird
  image_name: sb-obsrv-web-console
  tag: "1.0.0-GA"
  pullPolicy: "IfNotPresent"
ENV: development
PORT: 3000
APP_NAME: obsrv-web-console
PROMETHEUS_URL: http://obsrv-monitoring-prometheus.monitoring:9090
HTTPS: false
REACT_APP_VERSION: v1.2.0
GENERATE_SOURCEMAP: false
REACT_APP_GRAFANA_URL: http://localhost:80
REACT_APP_SUPERSET_URL: http://localhost:8081
service:
  type: NodePort