{{- if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: {{ include "prometheus-druid-exporter.fullname" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    release: monitoring
    system.monitoring: "true"
    {{- range $key, $value := .Values.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  name: {{ include "prometheus-druid-exporter.fullname" . }}
  namespace: {{ include "base.namespace" . }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    path: /metrics
    port: metrics
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- if .Values.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .ValuesserviceMonitor.relabelings | indent 4 }}
{{- end }}
{{- if .Values.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ toYaml .Values.serviceMonitor.metricRelabelings | indent 4 }}
{{- end }}
  namespaceSelector:
    matchNames:
    - {{ include "base.namespace" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "prometheus-druid-exporter.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      release: monitoring
{{- if .Values.serviceMonitor.targetLabels }}
  targetLabels:
{{- range .Values.serviceMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
{{- end -}}
