# templates/cronjob.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "base.namespace" . }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: {{ include "common.names.name" . }}
          annotations:
            checksum/config: {{ .Files.Glob "configs/*" | toYaml | sha256sum }}
            {{- if .Values.podAnnotations }}
            {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 12 }}
            {{- end }}
        spec:
          serviceAccountName: {{ include "base.serviceaccountname" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          initContainers:
            {{- toYaml .Values.initContainers | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{- include "base.image" .}}"
              imagePullPolicy: {{ .Values.imagePullPolicy }}
              {{- if .Values.livenessProbe }}
              livenessProbe:
                {{- toYaml .Values.livenessProbe | nindent 16 }}
              {{- end }}
              {{- if .Values.readinessProbe }}
              readinessProbe:
                {{- toYaml .Values.readinessProbe | nindent 16 }}
              {{- end }}
              ports:
                {{- range .Values.service.ports }}
                - name: {{ .name }}
                  containerPort: {{ .targetPort }}
                {{- end }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              envFrom:
              - configMapRef:
                  name: {{ include "common.names.fullname" . }}-env
              {{- if .Values.configmap.enabled }}
              volumeMounts:
              - name: config
                mountPath: {{ .Values.configmap.mountPath }}
              {{- end }}
            {{- with .Values.sidecars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          restartPolicy: OnFailure
          {{- if .Values.configmap.enabled }}
          volumes:
          - name: config
            configMap:
              name: {{ include "common.names.fullname" . }}
          {{- end }}
