apiVersion: v1
kind: ConfigMap
metadata:
  name: application-job-config
  namespace: {{ include "common.names.namespace" . | quote }}
data:
{{- if .Values.appdata }}
{{- range $key, $value := $.Values.appdata }}
  {{ $key }}: |+
{{ $value.conf | indent 4 }}
{{- end }}
{{- end }}
