{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ include "base.namespace" . }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
{{- $currentScope := .}}
{{- range $path, $_ := .Files.Glob "configs/*" }}
  {{- if and (not (contains "connectors" $path)) (ne $path "configs/env.yaml") }}
    {{ base $path | nindent 2 }}: |-
      {{- with $currentScope }}
      {{- $var := .Files.Get $path }}
      {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 6 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-env
  namespace: {{ include "base.namespace" . }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
  {{- end }}
data:
  {{- $var := .Files.Get "configs/env.yaml" }}
  {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connectors-config
  namespace: {{ include "base.namespace" . }}
  labels:
{{ include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "flink"
{{- if .Values.commonAnnotations }}
{{ include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
{{- end }}
data:
{{- $currentScope := .}}
{{- range $path, $_ := .Files.Glob "configs/*" }}
  {{- if and (contains "connectors" $path) (ne $path "configs/env.yaml") }}
    {{ base $path | nindent 2 }}: |-
      {{- with $currentScope }}
      {{- $var := .Files.Get $path }}
      {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 6 }}
      {{- end }}
  {{- end }}
{{- end }}
