apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-exporter.fullname" . }}
  namespace: {{ include "base.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "kafka-exporter.name" . }}
    helm.sh/chart: {{ include "kafka-exporter.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    release: monitoring
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "kafka-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
