{{- if not (lookup "v1" "Secret" .Release.Namespace "docker-registry-secret") -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.dockerconfigjson }}
kind: Secret
metadata:
  name: {{ .Values.docker_registry_secret_name }}
  namespace: {{ .Release.namespace }}
type: kubernetes.io/dockerconfigjson
{{- end -}}