{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark
  namespace: {{ include "base.namespace" . | quote }}
data:
{{- $currentScope := .}}
{{- range $path, $_ := .Files.Glob "configs/*" }}
  {{- if ne $path "configs/env.yaml" }}
    {{ base $path | nindent 2 }}: |-
      {{- with $currentScope }}
      {{- $var := .Files.Get $path }}
      {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 6 }}
      {{- end }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-env
  namespace: {{ include "base.namespace" . | quote }}
data:
  {{- $var := .Files.Get "configs/env.yaml" }}
  {{- include "common.tplvalues.render" (dict "value" $var "context" $) | nindent 2 }}