resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
serviceMonitor:
  enabled: true
  labels:
    release: monitoring
    system.monitoring: "true"
podLabels:
  system.monitoring: "true"