labels:
  system.storage: "true"
podLabels:
    system.storage: "true"
upgradeCRDs: true
image:
  repository: velero/velero
  tag: v1.13.0
credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=${velero_aws_access_key_id}
      aws_secret_access_key=${velero_aws_secret_access_key}
configuration:
  provider: ${cloud_provider}
  backupStorageLocation:
    bucket: ${velero_backup_bucket}
    config:
      region: ${velero_backup_bucket_region}
  volumeSnapshotLocation:
    name: default
    config:
      region: ${velero_backup_bucket_region}
initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws
    volumeMounts:
      - name: plugins
        mountPath: /target
metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: monitoring
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 512Mi

# Backup schedules to create.
schedules:
  obsrv-daily-backup:
    disabled: false
    schedule: "0 9,21 * * *"
    useOwnerReferencesInBackup: false
    template:
      ttl: "240h"
      includedNamespaces:
      - ${velero_namespace}