apiVersion: v1
kind: ConfigMap
metadata:
  name: lakehouse-connector-config
  namespace: {{ .Values.namespace }}
  labels:
    app: flink
    system.processing: "true"
data:
  base-config: |+
{{- include "common.tplvalues.render" (dict "value" .Values.base_config "context" $) | nindent 4 }}
{{- $name := "lakehouse-connector" }}
{{- with index .Values $name }}
{{- tpl (toYaml .) $ | nindent 2 }}
{{- end }}
  log4j_console_properties: |+
{{ .Values.log4j_console_properties | indent 4 }}
  core-site.xml: |+
    <configuration>
    {{- range $key, $value := .Values.hadoop_core_site }}
      <property>
        <name>{{ $key }}</name>
        <value>{{ $value }}</value>
      </property>
    {{- end }}
    </configuration>